name: Build and Push Docker Image

on:
  pull_request:
    types: [closed]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Build and Push Docker Image
      if: github.event.pull_request.merged == true
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: "${{ env.DOCKER_USERNAME }}:${{ env.GITHUB_SHA }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: "${{ env.DOCKER_USERNAME }}"
        password: "${{ env.DOCKER_PASSWORD }}"

